# Generated by Django 5.2 on 2025-04-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_water_alter_meal_calories_alter_meal_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Calorias (kcal)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carboidratos (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gordura (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=255, verbose_name='Nome da refeição'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proteína (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Água (mL)'),
        ),
    ]
