# Generated by Django 5.2 on 2025-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_calories_alter_meal_carbs_alter_meal_fat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gorduras (g)'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proteínas (g)'),
        ),
    ]
