# Generated by Django 5.2 on 2025-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='calories_goal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Calorias (kcal)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='carbs_goal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Carboidratos (g)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='fat_goal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Gorduras (g)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='protein_goal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Proteínas (g)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='water_goal',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Água (mL)'),
        ),
    ]
